# Generated by Django 5.2.17 on 2026-09-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
