# Generated by Django 5.2.17 on 2026-09-19 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_cartline_sold_in'),
        ('purchasing', '0002_payment_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='cash_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pos.cashmovement'),
        ),
    ]
