# Generated by Django 5.2.17 on 2026-09-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='method',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
