# Generated by Django 5.2.17 on 2026-09-19 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_credit_method'),
        ('pos', '0005_cartline_sold_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='cash_movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_entry', to='pos.cashmovement'),
        ),
    ]
