# Generated by Django 5.2.17 on 2026-09-23 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_credit_cash_movement'),
        ('selling', '0002_invoice_deliverynote_invoiceline_deliveryline'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_entries', to='selling.invoice'),
        ),
    ]
