# Generated by Django 5.2.17 on 2026-09-19 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('is_super', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_super', 'name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='platform_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admins', to='accounts.platformrole'),
        ),
    ]
