# Generated by Django 5.2.17 on 2026-09-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_platform_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='branch_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='invitation',
            name='pin_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='membership',
            name='all_branches',
            field=models.BooleanField(default=True),
        ),
    ]
