from django.urls import path

from apps.tenancy import admin_views as views

app_name = "platform"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("tenants/", views.tenant_list, name="tenant_list"),
    path("tenants/new/", views.tenant_create, name="tenant_create"),
    path("tenants/<int:pk>/", views.tenant_detail, name="tenant_detail"),
    path("tenants/<int:pk>/quick/", views.tenant_quick_view, name="tenant_quick_view"),
    path("tenants/<int:pk>/people/new/", views.tenant_member_form, name="tenant_member_create"),
    path("tenants/<int:pk>/people/<int:member_pk>/", views.tenant_member_form, name="tenant_member_edit"),
    path("tenants/<int:pk>/people/<int:member_pk>/remove/", views.tenant_member_remove, name="tenant_member_remove"),
    path("tenants/<int:pk>/edit/", views.tenant_edit, name="tenant_edit"),
    path("tenants/<int:pk>/plan/", views.tenant_change_plan, name="tenant_change_plan"),
    path("tenants/<int:pk>/suspend/", views.tenant_suspend, name="tenant_suspend"),
    path("tenants/<int:pk>/delete/", views.tenant_delete, name="tenant_delete"),
    path("tenants/<int:pk>/impersonate/", views.impersonate, name="impersonate"),
    path("support/end/", views.end_support, name="end_support"),
    path("users/", views.user_list, name="user_list"),
    path("users/new/", views.user_create, name="user_create"),
    path("users/<int:pk>/", views.user_detail, name="user_detail"),
    path("users/<int:pk>/delete/", views.user_delete, name="user_delete"),
    path("users/<int:pk>/quick/", views.user_quick_view, name="user_quick_view"),
    path("users/<int:pk>/edit/", views.user_edit, name="user_edit"),
    path("users/<int:pk>/password/", views.user_password, name="user_password"),
    path("users/<int:pk>/active/", views.user_toggle_active, name="user_toggle_active"),
    path("users/<int:pk>/platform/", views.user_platform_access, name="user_platform_access"),
    path("roles/", views.roles, name="roles"),
    path("roles/new/", views.role_edit, name="role_create"),
    path("roles/<int:pk>/", views.role_edit, name="role_edit"),
    path("roles/<int:pk>/delete/", views.role_delete, name="role_delete"),
    path("plans/", views.plans, name="plans"),
    path("plans/new/", views.plan_edit, name="plan_create"),
    path("plans/<int:pk>/", views.plan_edit, name="plan_edit"),
    path("plans/<int:pk>/delete/", views.plan_delete, name="plan_delete"),
    path("permissions/", views.permissions, name="permissions"),
    path("invoices/", views.invoices, name="invoices"),
    path("invoices/new/", views.invoice_create, name="invoice_create"),
    path("invoices/<int:pk>/", views.invoice_edit, name="invoice_edit"),
    path("invoices/<int:pk>/view/", views.invoice_detail, name="invoice_detail"),
    path("payments/<int:pk>/reverse/", views.payment_reverse, name="payment_reverse"),
    path("invoices/<int:pk>/pay/", views.invoice_pay, name="invoice_pay"),
    path("invoices/<int:pk>/void/", views.invoice_void, name="invoice_void"),
    path("devices/", views.devices, name="devices"),
    path("devices/<int:pk>/", views.device_edit, name="device_edit"),
    path("devices/<int:pk>/retire/", views.device_retire, name="device_retire"),
    path("devices/<int:pk>/delete/", views.device_delete, name="device_delete"),
    path("fiscal/retry/", views.fiscal_retry, name="fiscal_retry"),
    path("audit/", views.platform_audit, name="platform_audit"),
    path("health/", views.health, name="health"),
]
