# Generated by Django 5.2.17 on 2026-09-18 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyCash',
        ),
    ]
