# Generated by Django 5.2.17 on 2026-09-19 14:03

import apps.finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_delete_dailycash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='attachment',
            field=models.FileField(blank=True, upload_to=apps.finance.models.receipt_path),
        ),
    ]
