# Generated by Django 5.2.17 on 2026-09-19 17:25

import apps.core.storage
import apps.finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_private_receipts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='attachment',
            field=models.FileField(blank=True, storage=apps.core.storage.PrivateStorage(), upload_to=apps.finance.models.receipt_path),
        ),
    ]
