# Generated by Django 5.2.17 on 2026-09-19 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_move_receipts_private'),
        ('pos', '0005_cartline_sold_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='cash_movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense', to='pos.cashmovement'),
        ),
    ]
