# Generated by Django 5.2.17 on 2026-09-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_rls_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('last_started', models.DateTimeField(blank=True, null=True)),
                ('last_finished', models.DateTimeField(blank=True, null=True)),
                ('last_ok', models.BooleanField(default=True)),
                ('last_error', models.TextField(blank=True)),
                ('last_result', models.JSONField(blank=True, default=dict)),
                ('runs', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
