# Generated by Django 5.2.17 on 2026-09-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='queued',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
