# Generated by Django 5.2.17 on 2026-09-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_device_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
