"""
Allocating document numbers safely.

Sale numbers, receipt references and the rest are generated by reading the
highest one and adding one. That is fine in a single thread and wrong the
moment two tills sell in the same second: both read the same maximum, both
build the same number, and the unique constraint rejects the second.

The consequence is not cosmetic. The customer has already paid and the sale
is lost, which is the one failure this system must never produce. So the
insert is retried inside a savepoint until a number sticks.

A database sequence per tenant would avoid the retry, but it also gives up
the readable, gap-visible numbering that shops rely on when they read a
receipt number down the phone.
"""

import logging

from django.db import IntegrityError, transaction

logger = logging.getLogger(__name__)

MAX_ATTEMPTS = 8


def save_with_number(obj, *, field, generate, recover=None, attempts=MAX_ATTEMPTS):
    """
    Save ``obj``, re-allocating ``field`` if another writer took that number.

    ``recover`` is consulted on every failure. If it returns an object, that
    object is returned instead -- which is how an idempotent retry of the same
    offline sale resolves to the sale already stored rather than to a new one.
    """
    last_error = None

    for attempt in range(attempts):
        setattr(obj, field, generate())
        try:
            # A savepoint, so a rejected insert does not poison the
            # surrounding transaction and stop the retry.
            with transaction.atomic():
                obj.save()
            return obj
        except IntegrityError as exc:
            last_error = exc
            if recover is not None:
                found = recover()
                if found is not None:
                    return found
            logger.info(
                "Document number collision on %s (attempt %s): %s",
                type(obj).__name__, attempt + 1, getattr(obj, field),
            )

    raise last_error
