"""
Drop the switch that did nothing.

It offered to charge VAT on top of the price instead of out of it, on the rate row
-- and the till never read it. A shop that turned it off charged the customer
the same and declared the tax as though it were inside, which is the kind of
mistake nobody sees until somebody audits it.

Prices include VAT. That is how a shop here quotes, and now it is the only
thing the system can do rather than one of two things it claimed to.
"""

# Generated by Django 5.2.17 on 2026-09-22 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_taxrate_is_active_unit_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxrate',
            name='is_inclusive',
        ),
    ]
