# Generated by Django 5.2.17 on 2026-09-18 12:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('customers', '0001_initial'),
        ('inventory', '0002_initial'),
        ('org', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_offline_origin', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('held', 'Held'), ('converted', 'Sold'), ('abandoned', 'Abandoned')], default='open', max_length=12)),
                ('handoff_code', models.CharField(blank=True, db_index=True, max_length=8)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='org.branch')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='customers.customer')),
                ('price_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.pricelist')),
                ('register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='org.register')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CartLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=160)),
                ('qty', models.DecimalField(decimal_places=3, default=1, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('added_via', models.CharField(choices=[('scan', 'Scanner'), ('camera', 'Phone camera'), ('search', 'Search'), ('tile', 'Tile'), ('plu', 'Short code'), ('manual', 'Typed in')], default='search', max_length=10)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pos.cart')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.variant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_offline_origin', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(db_index=True, max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('voided', 'Voided'), ('refunded', 'Refunded'), ('part_refunded', 'Partly refunded')], default='completed', max_length=14)),
                ('sold_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('void_reason', models.CharField(blank=True, max_length=200)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('authorised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='org.branch')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='customers.customer')),
                ('register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='org.register')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sold_at'],
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_offline_origin', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(db_index=True, max_length=30)),
                ('reason', models.CharField(max_length=200)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('tigopesa', 'Tigo Pesa'), ('airtelmoney', 'Airtel Money'), ('card', 'Card'), ('credit', 'On account'), ('voucher', 'Voucher')], default='cash', max_length=14)),
                ('restock', models.BooleanField(default=True, help_text='Damaged goods come back without re-entering stock.')),
                ('authorised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='org.branch')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='pos.sale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FiscalReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Waiting to send'), ('sent', 'Sent'), ('failed', 'Failed'), ('not_required', 'Not required')], default='pending', max_length=14)),
                ('receipt_no', models.CharField(blank=True, max_length=60)),
                ('verification_code', models.CharField(blank=True, max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_receipt', to='pos.sale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=160)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('added_via', models.CharField(choices=[('scan', 'Scanner'), ('camera', 'Phone camera'), ('search', 'Search'), ('tile', 'Tile'), ('plu', 'Short code'), ('manual', 'Typed in')], default='search', max_length=10)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.batch')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pos.sale')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.variant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('return_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pos.return')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('sale_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='pos.saleline')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('tigopesa', 'Tigo Pesa'), ('airtelmoney', 'Airtel Money'), ('card', 'Card'), ('credit', 'On account'), ('voucher', 'Voucher')], max_length=14)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('change_given', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos.sale')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('opening_float', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('counted_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('variance_note', models.CharField(blank=True, max_length=200)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='org.branch')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='org.register')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='pos.shift'),
        ),
        migrations.AddField(
            model_name='return',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='pos.shift'),
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('pay_in', 'Money put in'), ('pay_out', 'Money taken out'), ('drop', 'Banked')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_movements', to='pos.shift')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['tenant', 'branch', 'status'], name='pos_cart_tenant__2315f8_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['tenant', 'branch', '-opened_at'], name='pos_shift_tenant__927051_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', 'branch', '-sold_at'], name='pos_sale_tenant__a60685_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', 'status', '-sold_at'], name='pos_sale_tenant__8d573a_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', '-sold_at'], name='pos_sale_tenant__bee430_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sale',
            unique_together={('tenant', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='return',
            unique_together={('tenant', 'number')},
        ),
    ]
