# Generated by Django 5.2.17 on 2026-09-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_sale_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='return',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='return',
            name='other_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
