# Generated by Django 5.2.17 on 2026-09-19 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_return_split_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartline',
            name='sold_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pos.sale'),
        ),
    ]
