# Generated by Django 5.2.17 on 2026-09-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_cartline_sold_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='sale',
            name='buyer_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
