# Generated by Django 5.2.17 on 2026-09-23 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_sale_buyer_name_phone'),
        ('selling', '0002_invoice_deliverynote_invoiceline_deliveryline'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='selling.invoice'),
        ),
    ]
